import os
import pathlib
import re
from openai import OpenAI

SOURCE_DIR = pathlib.Path("docs/es")
TARGET_DIR = pathlib.Path("docs/en")

AUTO_HEADER = (
    "<!-- AUTO-GENERATED FILE – DO NOT EDIT.\n"
    "     Source: docs/es (Spanish is source of truth)\n"
    "     This file is generated by GitHub Actions.\n"
    "-->\n\n"
)


def is_markdown(path: pathlib.Path) -> bool:
    return path.suffix.lower() in {".md", ".markdown"}


def strip_existing_auto_header(text: str) -> str:
    # remove our header if already present
    return re.sub(r"^<!-- AUTO-GENERATED FILE – DO NOT EDIT\.[\s\S]*?-->\n\n", "", text)


def translate_markdown(client: OpenAI, md: str) -> str:
    # Keep Markdown structure; avoid translating code blocks
    prompt = (
        "Translate this Markdown from Spanish to English.\n"
        "- Preserve Markdown formatting exactly.\n"
        "- Do NOT translate code blocks (``` ... ```), inline code (`...`), file paths, or URLs.\n"
        "- Keep technical terms consistent.\n"
        "Return only the translated Markdown.\n\n"
        "Markdown:\n"
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a careful technical translator for engineering documentation."},
            {"role": "user", "content": prompt + md},
        ],
        temperature=0.2,
    )
    return resp.choices[0].message.content


def main():
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("ERROR: OPENAI_API_KEY is missing. Configure it as a GitHub Actions secret.")

    client = OpenAI(api_key=api_key)

    if not SOURCE_DIR.exists():
        raise SystemExit(f"ERROR: {SOURCE_DIR} does not exist. Create docs/es/ first.")

    # Ensure target root exists
    TARGET_DIR.mkdir(parents=True, exist_ok=True)

    for src in SOURCE_DIR.rglob("*"):
        if src.is_dir():
            continue

        rel = src.relative_to(SOURCE_DIR)
        dst = TARGET_DIR / rel

        # Skip .gitkeep files
        if src.name == ".gitkeep":
            continue

        # Copy non-markdown files as-is (images, etc.)
        if not is_markdown(src):
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(src.read_bytes())
            print(f"Copied {rel}")
            continue

        src_text = src.read_text(encoding="utf-8")
        if not src_text.strip():
            continue

        print(f"Translating {rel}...")
        translated = translate_markdown(client, src_text)

        # Write with header
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(AUTO_HEADER + strip_existing_auto_header(translated), encoding="utf-8")
        print(f"  -> {dst}")


if __name__ == "__main__":
    main()
