/* Generado por herramientas/generar_sw.py: no editar a mano. */
'use strict';
const VERSION = '9af874e43bf2';
const CACHE = 'rcj-line-offline-' + VERSION;
const ARCHIVOS = [
  "LICENSE-rcj-rescue-cms.txt",
  "admin-corridas.html",
  "components/alertifyjs/dist/js/ngAlertify.js",
  "components/angular-animate/angular-animate.min.js",
  "components/angular-bootstrap-datetimepicker/src/css/datetimepicker.css",
  "components/angular-bootstrap-datetimepicker/src/js/datetimepicker.js",
  "components/angular-bootstrap-datetimepicker/src/js/datetimepicker.templates.js",
  "components/angular-bootstrap/dist/ui-bootstrap-csp.css",
  "components/angular-bootstrap/dist/ui-bootstrap-tpls.js",
  "components/angular-cookies/angular-cookies.min.js",
  "components/angular-datatables/demo/src/archives/dist/angular-datatables.min.js",
  "components/angular-sanitize/angular-sanitize.min.js",
  "components/angular-touch/angular-touch.min.js",
  "components/angular-translate-handler-log/angular-translate-handler-log.min.js",
  "components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js",
  "components/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js",
  "components/angular-translate-storage-local/angular-translate-storage-local.min.js",
  "components/angular-translate/angular-translate.min.js",
  "components/angular-ui-select/dist/select.min.css",
  "components/angular-ui-select/dist/select.min.js",
  "components/angular/angular.min.js",
  "components/bootstrap-fileinput/css/fileinput.min.css",
  "components/bootstrap-fileinput/img/loading-sm.gif",
  "components/bootstrap-fileinput/img/loading.gif",
  "components/bootstrap-fileinput/js/fileinput.min.js",
  "components/bootstrap-fileinput/js/locales/ja.js",
  "components/bootstrap/dist/css/bootstrap.min.css",
  "components/bootstrap/dist/js/bootstrap.min.js",
  "components/css-toggle-switch/dist/toggle-switch.css",
  "components/datatables/media/js/jquery.dataTables.min.js",
  "components/exceljs/index.js",
  "components/font-awesome-5/css/all.min.css",
  "components/font-awesome-5/webfonts/fa-brands-400.woff2",
  "components/font-awesome-5/webfonts/fa-regular-400.woff2",
  "components/font-awesome-5/webfonts/fa-solid-900.woff2",
  "components/html2canvas/index.js",
  "components/jSignature/libs/jSignature.min.js",
  "components/jquery-qrcode/jquery.qrcode.min.js",
  "components/jquery/dist/jquery.min.js",
  "components/lightbox2/dist/css/lightbox.min.css",
  "components/lightbox2/dist/images/close.png",
  "components/lightbox2/dist/images/loading.gif",
  "components/lightbox2/dist/images/next.png",
  "components/lightbox2/dist/images/prev.png",
  "components/lightbox2/dist/js/lightbox.min.js",
  "components/mobile-drag-drop/default.css",
  "components/mobile-drag-drop/index.min.js",
  "components/mobile-drag-drop/scroll-behaviour.min.js",
  "components/ng-file-upload/ng-file-upload-all.min.js",
  "components/pdfkit/js/pdfkit.standalone.js",
  "components/popper.js/dist/umd/popper.min.js",
  "components/qrcode-generator/qrcode.js",
  "components/socket.io-client/dist/socket.io.min.js",
  "components/sweetalert2/dist/sweetalert2.all.min.js",
  "configuracion.html",
  "corridas.html",
  "data/tilesets.json",
  "editor.html",
  "estadisticas.html",
  "firma.html",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "images/NoImage.png",
  "images/apple-touch-icon-144.png",
  "images/apple-touch-icon-152.png",
  "images/apple-touch-icon-180.png",
  "images/blackVictim.png",
  "images/deadVictim.png",
  "images/evacZone/green_lv2.png",
  "images/evacZone/green_lv2_a.png",
  "images/evacZone/red_lv2.png",
  "images/evacZone/red_lv2_a.png",
  "images/favicon-128.png",
  "images/favicon-16.ico",
  "images/favicon-196.png",
  "images/favicon-32.ico",
  "images/favicon-32.png",
  "images/favicon-96.ico",
  "images/favicon.ico",
  "images/greenVictim.png",
  "images/line_bonus.png",
  "images/liveVictim.png",
  "images/loader2.gif",
  "images/logo.png",
  "images/mapimage/bump1.png",
  "images/mapimage/bump2.png",
  "images/mapimage/bump3.png",
  "images/mapimage/bump4.png",
  "images/mapimage/bump5.png",
  "images/mapimage/down.png",
  "images/mapimage/obstacle.png",
  "images/mapimage/ramp.png",
  "images/mapimage/start.png",
  "images/mapimage/start2.png",
  "images/mapimage/up.png",
  "images/next-robot-done.png",
  "images/next-robot-undone.png",
  "images/nl_bonus.png",
  "images/noLogo.png",
  "images/rescueKit.png",
  "images/tiles/007.png",
  "images/tiles/009.png",
  "images/tiles/010.png",
  "images/tiles/011.png",
  "images/tiles/021.png",
  "images/tiles/022.png",
  "images/tiles/025.png",
  "images/tiles/ev-entrance.png",
  "images/tiles/ev-exit.png",
  "images/tiles/ev1.png",
  "images/tiles/ev2.png",
  "images/tiles/ev3.png",
  "images/tiles/exit.png",
  "images/tiles/seesaw.png",
  "images/tiles/tile-0.png",
  "images/tiles/tile-1.png",
  "images/tiles/tile-10.png",
  "images/tiles/tile-11.png",
  "images/tiles/tile-11_2.png",
  "images/tiles/tile-12.png",
  "images/tiles/tile-13.png",
  "images/tiles/tile-14.png",
  "images/tiles/tile-15.png",
  "images/tiles/tile-16.png",
  "images/tiles/tile-16_2.png",
  "images/tiles/tile-17.png",
  "images/tiles/tile-18.png",
  "images/tiles/tile-19.png",
  "images/tiles/tile-2.png",
  "images/tiles/tile-20.png",
  "images/tiles/tile-21.png",
  "images/tiles/tile-22.png",
  "images/tiles/tile-23.png",
  "images/tiles/tile-24.png",
  "images/tiles/tile-25.png",
  "images/tiles/tile-26.png",
  "images/tiles/tile-27.png",
  "images/tiles/tile-28.png",
  "images/tiles/tile-29.png",
  "images/tiles/tile-3.png",
  "images/tiles/tile-30.png",
  "images/tiles/tile-31.png",
  "images/tiles/tile-32.png",
  "images/tiles/tile-33.png",
  "images/tiles/tile-34.png",
  "images/tiles/tile-35.png",
  "images/tiles/tile-4.png",
  "images/tiles/tile-41.png",
  "images/tiles/tile-42.png",
  "images/tiles/tile-43.png",
  "images/tiles/tile-44.png",
  "images/tiles/tile-45.png",
  "images/tiles/tile-46.png",
  "images/tiles/tile-47.png",
  "images/tiles/tile-48.png",
  "images/tiles/tile-49.png",
  "images/tiles/tile-5.png",
  "images/tiles/tile-50.png",
  "images/tiles/tile-51.png",
  "images/tiles/tile-52.png",
  "images/tiles/tile-53.png",
  "images/tiles/tile-54.png",
  "images/tiles/tile-55.png",
  "images/tiles/tile-56.png",
  "images/tiles/tile-57.png",
  "images/tiles/tile-58.png",
  "images/tiles/tile-59.png",
  "images/tiles/tile-6.png",
  "images/tiles/tile-60.png",
  "images/tiles/tile-61.png",
  "images/tiles/tile-62.png",
  "images/tiles/tile-63.png",
  "images/tiles/tile-64.png",
  "images/tiles/tile-65.png",
  "images/tiles/tile-66.png",
  "images/tiles/tile-67.png",
  "images/tiles/tile-68.png",
  "images/tiles/tile-69.png",
  "images/tiles/tile-7.png",
  "images/tiles/tile-70.png",
  "images/tiles/tile-71.png",
  "images/tiles/tile-72.png",
  "images/tiles/tile-73.png",
  "images/tiles/tile-74.png",
  "images/tiles/tile-75.png",
  "images/tiles/tile-76.png",
  "images/tiles/tile-77.png",
  "images/tiles/tile-78.png",
  "images/tiles/tile-79.png",
  "images/tiles/tile-8.png",
  "images/tiles/tile-80.png",
  "images/tiles/tile-81-1.png",
  "images/tiles/tile-81-2.png",
  "images/tiles/tile-81.png",
  "images/tiles/tile-82.png",
  "images/tiles/tile-83.png",
  "images/tiles/tile-9.png",
  "images/tiles/tile-empty.png",
  "images/unknownVictim.png",
  "index.html",
  "javascripts/admin/games.js",
  "javascripts/admin/gamesPrint/line_2026.js",
  "javascripts/admin/mapEditor/line_2026.js",
  "javascripts/admin/maps.js",
  "javascripts/deflate.js",
  "javascripts/judge/line_2026.js",
  "javascripts/line_competition.js",
  "javascripts/lvl-uuid.js",
  "javascripts/makeQR.js",
  "javascripts/manual/line_2026.js",
  "javascripts/pathFinder.js",
  "javascripts/ranking/line_2026.js",
  "javascripts/sign/line_2026.js",
  "javascripts/translate_config.js",
  "juez.html",
  "lang/en.json",
  "lang/es.json",
  "lang/ja.json",
  "local/aviso-recorrido.js",
  "local/config.js",
  "local/estadisticas/calculo.js",
  "local/estadisticas/csv.js",
  "local/estadisticas/estadisticas.css",
  "local/estadisticas/graficos.js",
  "local/estadisticas/pagina.js",
  "local/http-backend.js",
  "local/io-shim.js",
  "local/nucleo/api.js",
  "local/nucleo/copy-properties.js",
  "local/nucleo/init-run.js",
  "local/nucleo/pathfinder-servidor.js",
  "local/nucleo/ranking.js",
  "local/nucleo/score-2026.js",
  "local/nucleo/store.js",
  "local/porcentaje-maximo.js",
  "local/pwa.js",
  "local/render/comun.js",
  "local/render/mapa-pdf.js",
  "local/render/mapa-png.js",
  "local/render/planilla-pdf.js",
  "local/render/registrar.js",
  "local/render/rutas-cms.js",
  "local/tactil.js",
  "local/timer-persistente.js",
  "local/ui/admin-corridas.js",
  "local/ui/comun.js",
  "local/ui/configuracion.js",
  "local/ui/estilos.css",
  "local/ui/inicio.js",
  "local/ui/mapas.js",
  "local/ui/movil-admin.css",
  "local/ui/movil-editor.css",
  "local/ui/movil-estadisticas.css",
  "local/ui/movil-firma.css",
  "local/ui/movil-juez.css",
  "local/ui/movil-manual-ranking.css",
  "local/ui/movil-salidas.css",
  "manifest.webmanifest",
  "manual.html",
  "mapas.html",
  "planillas.html",
  "ranking.html",
  "scoresheet_generation/line/after_final.png",
  "scoresheet_generation/line/after_finalE.png",
  "scoresheet_generation/line/base2024.png",
  "scoresheet_generation/line/checkpoint.png",
  "scoresheet_generation/line/checkpointE.png",
  "scoresheet_generation/line/element.png",
  "scoresheet_generation/line/obstacle.png",
  "scoresheet_generation/line/ramp.png",
  "scoresheet_generation/line/speedbump.png",
  "scoresheet_generation/line/start.png",
  "sounds/click.mp3",
  "sounds/click2.mp3",
  "sounds/error.mp3",
  "sounds/info.mp3",
  "sounds/timeup.mp3",
  "stylesheets/admin/live_ranking.css",
  "stylesheets/admin/mapEditor/line_modern.css",
  "stylesheets/admin/mapEditor/maze_modern.css",
  "stylesheets/common/modern_components.css",
  "stylesheets/common/modern_layout.css",
  "stylesheets/common/modern_list.css",
  "stylesheets/common/modern_modal.css",
  "stylesheets/fredrik.css",
  "stylesheets/navbar_premium.css",
  "stylesheets/style.css",
  "templates/line_editor_modal.html",
  "templates/line_judge_modal.html",
  "templates/line_view_modal.html",
  "templates/tile.html",
  "vista.html"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    for (let i = 0; i < ARCHIVOS.length; i += 20) {
      await Promise.all(ARCHIVOS.slice(i, i + 20).map(async (archivo) => {
        const respuesta = await fetch(new Request(archivo, { cache: 'reload' }));
        if (!respuesta.ok) throw new Error('No se pudo precargar ' + archivo + ' (' + respuesta.status + ')');
        await cache.put(archivo, respuesta);
      }));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const clave of await caches.keys()) {
      if (clave.startsWith('rcj-line-offline-') && clave !== CACHE) await caches.delete(clave);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const pedido = event.request;
  if (pedido.method !== 'GET') return;
  if (new URL(pedido.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // ignoreSearch: juez.html?run=... y templates/line_editor_modal.html?gs usan el mismo archivo.
    const guardado = await cache.match(pedido, { ignoreSearch: true });
    if (guardado) return guardado;
    try {
      return await fetch(pedido);
    } catch (error) {
      if (pedido.mode === 'navigate') {
        const inicio = await cache.match('index.html');
        if (inicio) return inicio;
      }
      throw error;
    }
  })());
});
